packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/sources/*'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lefthook: true
  less: true
  sharp: true
  unrs-resolver: true
