export type {
  AragonProposalMetadata,
  AragonProposalMetadataTable,
  AragonProposalMetadataUpdate,
  NewAragonProposalMetadata,
  ArchiveEventAragonVoting,
  ArchiveEventAragonVotingTable,
  NewArchiveEventAragonVoting,
  ArchiveEventDualGovernance,
  ArchiveEventDualGovernanceTable,
  NewArchiveEventDualGovernance,
  ArchiveEventEasyTrack,
  ArchiveEventEasyTrackTable,
  NewArchiveEventEasyTrack,
  DualGovernanceState,
  DualGovernanceStateHistory,
  DualGovernanceStateHistoryTable,
  DualGovernanceStateHistoryUpdate,
  NewDualGovernanceStateHistory,
  EasyTrackMotionMeta,
  EasyTrackMotionMetaTable,
  EasyTrackMotionMetaUpdate,
  EasyTrackMotionState,
  NewEasyTrackMotionMeta,
} from './persistence/schema';
