/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service metadata
     * @description Service banner for the API root. Unauthenticated.
     */
    get: operations['AppController_getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check service health
     * @description Liveness probe. Returns 200 while the process is serving; it does not check downstream dependencies. Unauthenticated.
     */
    get: operations['HealthController_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an actor
     * @description The profile for one address: its known identities and the DAOs it participates in. Addresses that have been merged into a canonical identity resolve here to that identity.
     */
    get: operations['ActorsController_getByAddress'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List an actor's proposals
     * @description Proposals authored by this address, newest first, across every indexed DAO unless narrowed with `dao`.
     */
    get: operations['ActorProposalsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List an actor's votes
     * @description Every vote this address has cast, newest first, across every indexed DAO unless narrowed with `dao`. Each row carries the proposal's own label for the choice — "for", "Option A" — resolved from the proposal it was cast on, or `null` where the proposal declares no label at that index.
     */
    get: operations['ActorVotesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List votes on a proposal
     * @description Every vote cast on this proposal, with the voter, choice, and voting power behind it. Filterable by voter and by choice — pass `primary_choice` to page through just the votes for one option.
     */
    get: operations['VotesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/votes/{voter_address}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get one address's vote
     * @description How a single address voted on this proposal, including the voting power it carried at the time. Returns 404 when the address did not vote.
     */
    get: operations['VotesController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List DAOs
     * @description Every DAO Kvorum indexes, with its slug, display name, and governance model. The slug is the identifier every other DAO-scoped endpoint takes in its path.
     */
    get: operations['DaoController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a DAO
     * @description One DAO in full, including the governance sources configured for it and any source-specific metadata.
     */
    get: operations['DaoController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a DAO's governance sources
     * @description The governance systems indexed for this DAO — an on-chain governor, a Snapshot space, a forum — each with the contract or space it reads from. A DAO's `source_type` values come from here, and those are what the proposal paths take.
     */
    get: operations['DaoController_sources'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/delegations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List delegation events
     * @description The DAO's delegation events in time order — each a delegator moving voting power to a delegate. Filterable by either end of the delegation and by block range. This is the event history; for who currently delegates to a given delegate, use the delegates endpoint.
     */
    get: operations['DelegationsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/delegates/{delegate_address}/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a delegate's current delegators
     * @description The set of addresses currently delegating to this delegate, with the power each contributes. Pass `as_of_block_number` to reconstruct the set as it stood at a past block.
     */
    get: operations['DelegationsController_current'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/actors/{address}/delegation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an actor's outgoing delegation
     * @description Where this address currently delegates its voting power within the DAO, if anywhere. The mirror of the delegators endpoint, looking outward from one actor.
     */
    get: operations['DelegationsController_actorDelegation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a DAO's proposals
     * @description Proposals belonging to one DAO, newest first by default. Each row carries its current state and a per-choice tally summary; `null` means no votes have been recorded yet. Filterable by state, source type, proposer, whether the proposal is binding, and the voting window.
     */
    get: operations['ProposalController_listByDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a proposal
     * @description One proposal in full: description, decoded on-chain actions, declared choices, and the originating chain. Includes the AI summary and calldata-mismatch verdict inline when they have been computed — both are `null` for a proposal the AI pipeline has not processed, which is not an error.
     */
    get: operations['ProposalController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/ai/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the AI summary
     * @description The model-written plain-language summary of a proposal, with the model, prompt version, and confidence that produced it. Returns 404 when no summary has been generated — use the `ai_summary` field on the proposal detail response if you would rather treat absence as a null field than an error.
     */
    get: operations['ProposalController_aiSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/ai/mismatch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the calldata-mismatch analysis
     * @description The full analysis behind the mismatch flag: whether the proposal's executable calldata does what its description claims, with per-action findings and the model's reasoning. Returns 404 when the proposal has not been analysed.
     */
    get: operations['ProposalController_aiMismatch'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/similar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Find similar proposals
     * @description Proposals across every indexed DAO whose text is semantically closest to this one, ranked by embedding distance. Narrowable by DAO, source type, and time window. Degrades to an empty list — never a 404 — when the target has no embedding yet.
     */
    get: operations['ProposalController_similarProposals'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/ai/forum-synthesis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the forum-discussion synthesis
     * @description A synthesis of the linked forum thread: the themes raised, sentiment, and points of contention. Returns 404 when the proposal has no linked thread or the thread has not been synthesised. A thread skipped for being non-English returns 200 with `data: null` and a reason in `_meta`.
     */
    get: operations['ProposalController_aiForumSynthesis'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/tally': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the vote tally
     * @description Current vote totals per choice, summed from indexed vote events at the confirmed head. Choices the proposal declared but which received no votes are present with a zero total, so the shape is stable for the whole voting period.
     */
    get: operations['ProposalController_tally'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List proposals across all DAOs
     * @description The cross-DAO proposal feed, newest first by default. Same shape as the per-DAO listing, with a `dao` filter instead of a path parameter — use this to follow governance activity across every indexed DAO in one paginated stream.
     */
    get: operations['ProposalController_listCrossDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/analytics/cross-dao': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an actor's cross-DAO activity
     * @description One address's governance footprint across every DAO it participates in — where it votes, where it holds or receives delegated power, and how active it is in each.
     */
    get: operations['ActorAnalyticsController_crossDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/proposal-pass-rate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get proposal pass rate over time
     * @description The share of a DAO's proposals that passed, bucketed over a time window. Use it to see whether a DAO's proposals are becoming more or less likely to succeed. Narrowable to a single proposal type.
     */
    get: operations['DaoAnalyticsController_passRate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/participation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get participation rate over time
     * @description The share of eligible voting power that actually voted, bucketed over a time window. Computed per proposal as cast VP / eligible VP, then averaged per bucket. Only proposals with eligible VP data contribute.
     */
    get: operations['DaoAnalyticsController_participation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/concentration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get voting-power concentration
     * @description How concentrated a DAO's voting power is over time — the share held by the largest holders, bucketed across the window. Returns 204 when no power-bearing delegation exists anywhere in the window.
     */
    get: operations['DaoAnalyticsController_concentration'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/delegation-flow': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the delegation graph
     * @description Delegation as a graph for the window: nodes are addresses, edges are delegations weighted by the power moved. Use `min_voting_power` to drop noise. An edge whose endpoint has no known actor is still returned — an undelegation to the zero address, for example — it simply contributes no node.
     */
    get: operations['DaoAnalyticsController_delegationFlow'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/delegates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the delegate leaderboard
     * @description A DAO's delegates ranked by current voting power, with the number of delegators behind each.
     */
    get: operations['DaoAnalyticsController_delegateLeaderboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/delegate-alignment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get delegate voting alignment
     * @description How often a delegate votes the same way as its peers, over a window. Use it to spot delegates that consistently vote with — or against — the rest of the delegate set.
     */
    get: operations['DaoAnalyticsController_delegateAlignment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/forum-activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get forum activity over time
     * @description Forum post volume for a DAO's Discourse governance category, bucketed over a time window. Derived from crawled thread data in the archive.
     */
    get: operations['DaoAnalyticsController_forumActivity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search across proposals, DAOs, and actors
     * @description Full-text search with ranked results per entity type. Automatically detects hex addresses and routes to direct address lookup for actors.
     */
    get: operations['SearchController_search'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/forum/{external_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a forum thread
     * @description A Discourse thread linked to a DAO's governance, with its posts. `external_id` is the Discourse topic id, as reported in a proposal's off-chain discussion links.
     */
    get: operations['ForumThreadController_getThread'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/forum/{external_id}/ai/synthesis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the AI synthesis of a forum thread
     * @description A synthesis of the thread's discussion: arguments for and against, unresolved concerns, notable participants, and overall sentiment. Content-addressed by the thread's raw content — the same stored analysis the proposal route serves. Returns 404 when the thread is unknown, has no content, or has not been synthesised; a thread skipped for being non-English returns 200 with `data: null` and a reason in `_meta`.
     */
    get: operations['ForumThreadController_getThreadSynthesis'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActorAddressDto: {
      address: string;
      is_primary: boolean;
      source: string;
    };
    ActorDto: {
      actor_id: string;
      primary_address: string;
      display_name?: Record<string, never> | null;
      all_addresses: components['schemas']['ActorAddressDto'][];
    };
    ActorResponseDto: {
      data: components['schemas']['ActorDto'];
    };
    ProblemDto: {
      type: string;
      title: string;
      status: number;
      detail: string;
      instance: string;
      violations?: Record<string, never>[];
    };
    ActorProposalMetaDto: {
      confirmed: boolean;
    };
    ActorProposalListItemDto: {
      proposal_id: string;
      source_type: string;
      dao_slug: string;
      title?: Record<string, never> | null;
      state: string;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      created_at: string;
      _meta: components['schemas']['ActorProposalMetaDto'];
    };
    PaginationDto: {
      limit: number;
      next_cursor: Record<string, never> | null;
      has_more: boolean;
    };
    ActorProposalListResponseDto: {
      data: components['schemas']['ActorProposalListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    EmbeddedProposalLinksDto: {
      proposal: string;
    };
    EmbeddedProposalMetaDto: {
      links: components['schemas']['EmbeddedProposalLinksDto'];
    };
    EmbeddedProposalDto: {
      proposal_id: string;
      source_type: string;
      dao_slug: string;
      title?: Record<string, never> | null;
      state: string;
      created_at: string;
      voting_ends_at?: Record<string, never> | null;
      _meta: components['schemas']['EmbeddedProposalMetaDto'];
    };
    ActorVoteMetaDto: {
      confirmed: boolean;
    };
    ActorVoteListItemDto: {
      vote_id: string;
      voting_chain_id: string;
      proposal: components['schemas']['EmbeddedProposalDto'];
      primary_choice?: Record<string, never> | null;
      /** @description The proposal’s declared label for primary_choice, e.g. "for". Null when the proposal declares no choice at that index, so the client can fall back rather than invent one. */
      choice_label?: string | null;
      voting_power_reported: string;
      cast_at: Record<string, never> | null;
      _meta: components['schemas']['ActorVoteMetaDto'];
    };
    ActorVoteListResponseDto: {
      data: components['schemas']['ActorVoteListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    ActorLinkDto: {
      actor: string;
    };
    EmbeddedActorMetaDto: {
      links: components['schemas']['ActorLinkDto'];
    };
    VoterDto: {
      address: string;
      display_name?: Record<string, never> | null;
      _meta: components['schemas']['EmbeddedActorMetaDto'];
    };
    VoteMetaDto: {
      confirmed: boolean;
    };
    VoteListItemDto: {
      vote_id: string;
      voting_chain_id: string;
      voter: components['schemas']['VoterDto'];
      voting_power_reported: string;
      voting_power_verified: boolean;
      primary_choice: Record<string, never> | null;
      cast_at: Record<string, never> | null;
      reason?: Record<string, never> | null;
      _meta: components['schemas']['VoteMetaDto'];
    };
    VoteListResponseDto: {
      data: components['schemas']['VoteListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    VoteChoiceDto: {
      choice_index: number;
      weight: string;
    };
    VoteDetailDto: {
      vote_id: string;
      voting_chain_id: string;
      voter: components['schemas']['VoterDto'];
      voting_power_reported: string;
      voting_power_verified: boolean;
      primary_choice: Record<string, never> | null;
      cast_at: Record<string, never> | null;
      reason?: Record<string, never> | null;
      _meta: components['schemas']['VoteMetaDto'];
      choices: components['schemas']['VoteChoiceDto'][];
    };
    VoteDetailResponseDto: {
      data: components['schemas']['VoteDetailDto'] | null;
    };
    DaoLinksDto: {
      self: string;
    };
    DaoMetaDto: {
      last_updated_at: string;
      links: components['schemas']['DaoLinksDto'];
    };
    DaoListItemDto: {
      slug: string;
      name: string;
      description: string;
      website_url: string;
      forum_url: string;
      primary_token_address: string;
      primary_chain_id: string;
      _meta: components['schemas']['DaoMetaDto'];
    };
    DaoListResponseDto: {
      data: components['schemas']['DaoListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    DaoSourceDto: {
      source_type: string;
      config: {
        [key: string]: string | string[];
      };
    };
    DaoDetailDto: {
      slug: string;
      name: string;
      description: string;
      website_url: string;
      forum_url: string;
      primary_token_address: string;
      primary_chain_id: string;
      _meta: components['schemas']['DaoMetaDto'];
      sources: components['schemas']['DaoSourceDto'][];
    };
    DaoDetailResponseDto: {
      data: components['schemas']['DaoDetailDto'];
    };
    DaoSourceListResponseDto: {
      data: components['schemas']['DaoSourceDto'][];
    };
    DelegationActorLinksDto: {
      actor: string;
    };
    DelegationActorMetaDto: {
      links: components['schemas']['DelegationActorLinksDto'];
    };
    DelegationActorDto: {
      address: string;
      display_name?: Record<string, never> | null;
      _meta: components['schemas']['DelegationActorMetaDto'];
    };
    DelegationListItemDto: {
      delegation_id: string;
      delegator: components['schemas']['DelegationActorDto'];
      delegate: components['schemas']['DelegationActorDto'] | null;
      voting_power: string;
      block_number: string;
      event_type: string;
      /** @enum {string} */
      model: 'relationship-only' | 'power-bearing';
      tx_hash: string;
      created_at: Record<string, never> | null;
    };
    DelegationListResponseDto: {
      data: components['schemas']['DelegationListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    CurrentDelegatorsMetaDto: {
      as_of_block_number: string;
    };
    CurrentDelegatorsResponseDto: {
      data: components['schemas']['DelegationListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
      _meta: components['schemas']['CurrentDelegatorsMetaDto'];
    };
    OffchainDelegationDto: {
      platform: string;
      system: string;
      scope?: Record<string, never> | null;
      network: string;
      delegate_address: string;
      weight?: Record<string, never> | null;
      expires_at?: Record<string, never> | null;
    };
    ActorDelegationDto: {
      evm?: components['schemas']['DelegationListItemDto'] | null;
      offchain: components['schemas']['OffchainDelegationDto'][];
    };
    ActorDelegationResponseDto: {
      data: components['schemas']['ActorDelegationDto'];
    };
    ProposerDto: {
      address: string;
      display_name?: Record<string, never> | null;
    };
    ProposalTallySummaryChoiceDto: {
      choice_index: number;
      /** @description The declared choice label, e.g. "for" — for client-side classification. */
      label: string;
      /** @description Share of participating power, 0–100, to two decimals. */
      pct: number;
    };
    ProposalTallySummaryDto: {
      choices: components['schemas']['ProposalTallySummaryChoiceDto'][];
    };
    ProposalLinksDto: {
      self: string;
      votes: string;
    };
    ProposalMetaDto: {
      confirmed: boolean;
      last_updated_at: string;
      links: components['schemas']['ProposalLinksDto'];
    };
    ProposalListItemDto: {
      dao_slug: string;
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      state: string;
      binding: boolean;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      proposer: components['schemas']['ProposerDto'];
      /** @description Per-choice voting-power tally for the row bars; null when no votes are cast yet. */
      tally?: components['schemas']['ProposalTallySummaryDto'] | null;
      _meta: components['schemas']['ProposalMetaDto'];
    };
    ProposalListResponseDto: {
      data: components['schemas']['ProposalListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    AragonProposalMetadataDto: {
      /** @enum {string} */
      kind: 'aragon_voting';
      app_address: string;
      app_version?: Record<string, never> | null;
      support_required_pct?: Record<string, never> | null;
      min_accept_quorum_pct?: Record<string, never> | null;
      main_phase_ends_at?: Record<string, never> | null;
      objection_phase_ends_at?: Record<string, never> | null;
      executed_at?: Record<string, never> | null;
    };
    SnapshotProposalMetadataDto: {
      /** @enum {string} */
      kind: 'snapshot';
      space_id: string;
      voting_type?: Record<string, never> | null;
      strategies?: Record<string, never> | null;
      ipfs_hash?: Record<string, never> | null;
      network?: Record<string, never> | null;
      scores_state?: Record<string, never> | null;
      flagged: boolean;
      /** @description Per-choice voting-power tally (0-indexed), summed from the full vote breakdown. Present for approval and weighted/quadratic proposals (whose tally the single primary_choice cannot represent); null otherwise. */
      choice_scores?: number[] | null;
    };
    DualGovernanceProposalMetadataDto: {
      /** @enum {string} */
      kind: 'dual_governance';
      /** @enum {string} */
      origin: 'aragon' | 'direct';
      dg_proposal_id: string;
      /** @enum {string} */
      status: 'submitted' | 'scheduled' | 'executed' | 'cancelled';
      executor: string;
      aragon_source_id?: Record<string, never> | null;
      submitted_at: string;
      scheduled_at?: Record<string, never> | null;
      executed_at?: Record<string, never> | null;
      cancelled_at?: Record<string, never> | null;
    };
    EasyTrackProposalMetadataDto: {
      /** @enum {string} */
      kind: 'easy_track';
      motion_id: string;
      factory_address: string;
      objection_ends_at: string;
      /** @enum {string} */
      state: 'active' | 'enacted' | 'objected' | 'rejected' | 'canceled';
    };
    ProposalActionDto: {
      action_index: number;
      target_address: string;
      target_chain_id: string;
      value_wei: string;
      function_signature?: Record<string, never> | null;
      calldata: string;
      decoded_function?: Record<string, never> | null;
      decoded_arguments?: Record<string, never> | null;
    };
    ProposalChoiceDto: {
      choice_index: number;
      value: string;
    };
    ProposalVotingDto: {
      voting_chain_id?: Record<string, never> | null;
      voting_machine_address?: Record<string, never> | null;
      voting_strategy_address?: Record<string, never> | null;
      creation_block: string;
    };
    ProposalPayloadDto: {
      payload_index: number;
      payload_id: string;
      payloads_controller_address: string;
      status: string;
      executed_at_destination?: Record<string, never> | null;
      unindexed_target_chain: boolean;
    };
    ProposalPayloadGroupDto: {
      target_chain_id: string;
      payloads: components['schemas']['ProposalPayloadDto'][];
    };
    OffchainDiscussionLinkDto: {
      platform: string;
      host: string;
      url: string;
      title?: Record<string, never> | null;
      /** @enum {string} */
      confidence: 'high' | 'medium' | 'low';
      last_activity_at?: Record<string, never> | null;
    };
    ProposalAiSummaryKeyChangeDto: {
      description: string;
      /** @description high | medium | low */
      significance: string;
    };
    ProposalAiSummaryMetaDto: {
      /**
       * @description Always true — labels AI-generated content.
       * @example true
       */
      ai_generated: boolean;
      model: string;
      prompt_version: string;
      /** @description sha256: of the summarized input (description + decoded actions). */
      input_hash: string;
      generated_at: string;
    };
    ProposalAiSummaryDto: {
      tldr: string;
      proposal_type: string;
      /** @description high | medium | low */
      proposal_type_confidence: string;
      affected_contracts: string[];
      key_changes: components['schemas']['ProposalAiSummaryKeyChangeDto'][];
      beneficiaries?: string[];
      funding_amount_usd: string | null;
      notable_concerns?: string[];
      _meta: components['schemas']['ProposalAiSummaryMetaDto'];
    };
    ProposalAiMismatchMetaDto: {
      /**
       * @description Always true — labels AI-generated content.
       * @example true
       */
      ai_generated: boolean;
      model: string;
      prompt_version: string;
      /** @description sha256: of the analyzed input (description + decoded actions). */
      input_hash: string;
      generated_at: string;
    };
    ProposalAiMismatchFlagDto: {
      /** @description material_discrepancy | severe_discrepancy */
      assessment: string;
      /** @description The highest-severity discrepancy's description. */
      summary: string;
      _meta: components['schemas']['ProposalAiMismatchMetaDto'];
    };
    ProposalDetailDto: {
      dao_slug: string;
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      state: string;
      binding: boolean;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      proposer: components['schemas']['ProposerDto'];
      /** @description Per-choice voting-power tally for the row bars; null when no votes are cast yet. */
      tally?: components['schemas']['ProposalTallySummaryDto'] | null;
      _meta: components['schemas']['ProposalMetaDto'];
      description: string;
      actions: components['schemas']['ProposalActionDto'][];
      choices: components['schemas']['ProposalChoiceDto'][];
      origin_chain_id: string;
      voting?: components['schemas']['ProposalVotingDto'] | null;
      payloads?: components['schemas']['ProposalPayloadGroupDto'][] | null;
      metadata?:
        | (
            | components['schemas']['AragonProposalMetadataDto']
            | components['schemas']['SnapshotProposalMetadataDto']
            | components['schemas']['DualGovernanceProposalMetadataDto']
            | components['schemas']['EasyTrackProposalMetadataDto']
          )
        | null;
      offchain_discussion_links: components['schemas']['OffchainDiscussionLinkDto'][];
      /** @description AI-generated summary + provenance _meta; null when not yet produced or capped. */
      ai_summary?: components['schemas']['ProposalAiSummaryDto'] | null;
      /** @description Conservative calldata-vs-prose mismatch flag + provenance _meta. Null when no analysis exists (non-binding, undecoded, unprocessed, or capped) or when the analysis found no material/severe, confident discrepancy. The full analysis is at the dedicated /ai/mismatch endpoint. */
      ai_mismatch_flag?: components['schemas']['ProposalAiMismatchFlagDto'] | null;
    };
    ProposalDetailResponseDto: {
      data: components['schemas']['ProposalDetailDto'];
    };
    ProposalAiSummaryResponseDto: {
      data: components['schemas']['ProposalAiSummaryDto'];
    };
    MismatchDescriptionActionDto: {
      /** @description A claim the proposal's prose makes about what it does. */
      claim: string;
      /** @description Brief reference to where in the description the claim appears. */
      location: string;
    };
    MismatchCalldataActionDto: {
      action_index: number;
      /** @description Plain-language summary of what the decoded calldata action does. */
      summary: string;
      /** @description high | medium | low */
      significance: string;
    };
    MismatchDiscrepancyDto: {
      /** @description value_mismatch | omitted_in_description | extra_in_description | misleading_phrasing | target_mismatch */
      type: string;
      description: string;
      /** @description high | medium | low */
      severity: string;
      description_excerpt: string | null;
      related_action_indices: number[];
    };
    ProposalMismatchDto: {
      /** @description consistent | minor_discrepancy | material_discrepancy | severe_discrepancy */
      overall_assessment: string;
      /** @description high | medium | low */
      confidence: string;
      description_actions: components['schemas']['MismatchDescriptionActionDto'][];
      calldata_actions: components['schemas']['MismatchCalldataActionDto'][];
      discrepancies: components['schemas']['MismatchDiscrepancyDto'][];
      /** @description The model's explanation of its assessment (shown to users). */
      reasoning: string;
      _meta: components['schemas']['ProposalAiMismatchMetaDto'];
    };
    ProposalMismatchResponseDto: {
      data: components['schemas']['ProposalMismatchDto'];
    };
    SimilarProposalItemDto: {
      dao_slug: string;
      dao_name: string;
      source_type: string;
      source_id: string;
      title: string | null;
      state: string;
      created_at: string;
      voting_starts_at: string | null;
      voting_ends_at: string | null;
      /** @description Cosine similarity in [-1, 1] (1 = identical). */
      similarity: number;
    };
    SimilarProposalsMetaDto: {
      /**
       * @description Always true — labels AI-derived content (SPEC §5.2).
       * @example true
       */
      ai_generated: boolean;
      /** @description The embedding model + composition version the ranking used. */
      embedding_version: string;
    };
    SimilarProposalsResponseDto: {
      data: components['schemas']['SimilarProposalItemDto'][];
      _meta: components['schemas']['SimilarProposalsMetaDto'];
    };
    ForumArgumentDto: {
      summary: string;
      /** @description Handles of participants making this argument (≤5). */
      supporting_participants: string[];
    };
    ForumConcernDto: {
      summary: string;
      /** @description Handles of participants who raised it (≤3). */
      raised_by: string[];
    };
    ForumParticipantDto: {
      handle: string;
      role_summary: string;
    };
    ForumSynthesisDto: {
      arguments_for: components['schemas']['ForumArgumentDto'][];
      arguments_against: components['schemas']['ForumArgumentDto'][];
      unresolved_concerns: components['schemas']['ForumConcernDto'][];
      notable_participants: components['schemas']['ForumParticipantDto'][];
      /** @enum {string} */
      sentiment: 'favorable' | 'mixed' | 'unfavorable' | 'contentious';
      /** @enum {string} */
      thread_health: 'constructive' | 'mixed' | 'unproductive';
    };
    ForumSynthesisMetaDto: {
      /**
       * @description Labels AI-derived content (SPEC §5.2). false when the thread was skipped.
       * @example true
       */
      ai_generated: boolean;
      /** @description Model that produced the synthesis (Haiku or Sonnet). */
      model?: string;
      prompt_version?: string;
      /** @description sha256: of the synthesized thread `raw_content`. */
      input_hash?: string;
      generated_at?: string;
      /**
       * @description Present when the thread was not synthesized (KNOWN-016); `data` is then null.
       * @enum {string}
       */
      skipped_reason?: 'non_english';
    };
    ForumSynthesisResponseDto: {
      data: components['schemas']['ForumSynthesisDto'] | null;
      _meta: components['schemas']['ForumSynthesisMetaDto'];
    };
    ProposalTallyChoiceDto: {
      choice_index: number;
      /** @description Summed voting power for the choice. UInt256 base units when source=votes; the raw per-choice score when source=choice_scores — interpret via `source`. */
      voting_power: string;
      voter_count: number;
      /** @description Share of participating power, 0–100, to two decimals. */
      pct: number;
    };
    ProposalTallyDto: {
      choices: components['schemas']['ProposalTallyChoiceDto'][];
      total_voting_power: string;
      total_voters: number;
      /**
       * @description Where the tally came from: `votes` (summed primary_choice) or `choice_scores` (a source-provided per-choice breakdown for approval/weighted proposals).
       * @enum {string}
       */
      source: 'votes' | 'choice_scores';
    };
    ProposalTallyResponseDto: {
      data: components['schemas']['ProposalTallyDto'];
    };
    CrossDaoSummaryDto: {
      dao_slug: string;
      votes_cast: number;
      proposals_proposed: number;
      current_voting_power: string;
      last_active_at?: Record<string, never> | null;
      alignment_with_majority_pct?: Record<string, never> | null;
    };
    AnalyticsMetaDto: {
      confirmed: boolean;
      derived_through?: Record<string, never> | null;
    };
    CrossDaoActorDto: {
      address: string;
      actor_id: string;
      daos: components['schemas']['CrossDaoSummaryDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    PassRateRowDto: {
      source_type: string;
      bucket: string;
      passed: number;
      failed: number;
      pass_rate?: Record<string, never> | null;
    };
    PassRateResponseDto: {
      data: components['schemas']['PassRateRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ParticipationRowDto: {
      source_type: string;
      bucket: string;
      participation_rate?: Record<string, never> | null;
      proposal_count: number;
      proposals_with_data: number;
    };
    ParticipationResponseDto: {
      data: components['schemas']['ParticipationRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ForumActivityRowDto: {
      bucket: string;
      post_count: number;
    };
    ForumActivityResponseDto: {
      data: components['schemas']['ForumActivityRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ConcentrationTopShareDto: {
      n_1: number;
      n_5: number;
      n_10: number;
      n_20: number;
    };
    ConcentrationRowDto: {
      bucket: string;
      gini: number;
      top_share: components['schemas']['ConcentrationTopShareDto'];
      effective_delegate_count: number;
      total_voting_power: string;
      delegate_count: number;
    };
    ConcentrationResponseDto: {
      data: components['schemas']['ConcentrationRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    DelegationFlowNodeDto: {
      actor_id: string;
      primary_address: string;
      display_name?: Record<string, never> | null;
      current_voting_power: string;
    };
    DelegationFlowEdgeDto: {
      delegator_actor_id: string;
      delegate_actor_id?: Record<string, never> | null;
      voting_power: string;
      block_number: string;
      event_type: string;
      created_at: string;
    };
    DelegationFlowResponseDto: {
      nodes: components['schemas']['DelegationFlowNodeDto'][];
      edges: components['schemas']['DelegationFlowEdgeDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    DelegateLeaderboardRowDto: {
      /** @description 1-based rank by current received voting power. */
      rank: number;
      actor_id: string;
      address: string;
      display_name?: Record<string, never> | null;
      /** @description Current received voting power, base units (UInt256 as string). */
      voting_power: string;
      /** @description Share of the DAO-wide delegated voting power, 0..1. */
      voting_power_share: number;
      /** @description Number of addresses currently delegating to this delegate. */
      delegator_count: number;
    };
    DelegateLeaderboardResponseDto: {
      data: components['schemas']['DelegateLeaderboardRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    DelegateAlignmentFocalDto: {
      actor_id: string;
      address: string;
      display_name?: Record<string, never> | null;
    };
    DelegateAlignmentPeerDto: {
      actor_id: string;
      address: string;
      display_name?: Record<string, never> | null;
      vote_count: number;
      shared_proposals: number;
      alignment_score: number;
    };
    DelegateAlignmentResponseDto: {
      focal_delegate: components['schemas']['DelegateAlignmentFocalDto'];
      peers: components['schemas']['DelegateAlignmentPeerDto'][];
      pagination: components['schemas']['PaginationDto'];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ProposalSearchItemDto: {
      dao_slug: string;
      dao_name: string;
      source_type: string;
      source_id: string;
      title?: Record<string, never> | null;
      state: string;
      voting_starts_at?: Record<string, never> | null;
      rank: number;
    };
    DaoSearchItemDto: {
      slug: string;
      name: string;
      description: string;
      rank: number;
    };
    ActorSearchItemDto: {
      display_name?: Record<string, never> | null;
      primary_address: string;
      rank: number;
    };
    SearchDataDto: {
      proposals: components['schemas']['ProposalSearchItemDto'][];
      daos: components['schemas']['DaoSearchItemDto'][];
      actors: components['schemas']['ActorSearchItemDto'][];
    };
    SearchResponseDto: {
      data: components['schemas']['SearchDataDto'];
    };
    ForumThreadLinkedProposalDto: {
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      /** @enum {string} */
      confidence: 'high' | 'medium' | 'low';
    };
    ForumThreadDto: {
      /** @description Discourse topic id (the {external_id} in the URL). */
      external_id: string;
      host: string;
      /** @description Canonical link to the thread on the source Discourse instance. */
      source_url: string;
      title: Record<string, never> | null;
      /** @description Concatenated post bodies (the ingested thread content); no per-post breakdown. */
      raw_content: Record<string, never> | null;
      post_count: Record<string, never> | null;
      last_activity_at: Record<string, never> | null;
      linked_proposals: components['schemas']['ForumThreadLinkedProposalDto'][];
    };
    ForumThreadResponseDto: {
      data: components['schemas']['ForumThreadDto'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActorsController_getByAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorResponseDto'];
        };
      };
      /** @description Redirect to canonical primary address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorProposalsController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: created_at, voting_starts_at. */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorProposalListResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorVotesController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: cast_at, voting_power_reported. */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorVoteListResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  VotesController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: cast_at, voting_power_reported. */
        sort?: string;
        voter?: string;
        /** @description Comma-delimited primary_choice values */
        primary_choice?: string;
      };
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoteListResponseDto'];
        };
      };
      /** @description Redirect to canonical voter filter */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  VotesController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
        voter_address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoteDetailResponseDto'];
        };
      };
      /** @description Redirect to canonical voter address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: slug, created_at. */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoDetailResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_sources: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoSourceListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: block_number, created_at. */
        sort?: string;
        delegator?: string;
        delegate?: string;
        from_block_min?: string;
        from_block_max?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegationListResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_current: {
    parameters: {
      query?: {
        as_of_block_number?: string;
      };
      header?: never;
      path: {
        slug: string;
        delegate_address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentDelegatorsResponseDto'];
        };
      };
      /** @description Redirect to canonical delegate address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_actorDelegation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorDelegationResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_listByDao: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: voting_starts_at, voting_ends_at, created_at, state_updated_at. */
        sort?: string;
        /** @description Comma-delimited state values */
        state?: string;
        source_type?: string;
        proposer?: string;
        binding?: string;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalDetailResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_aiSummary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalAiSummaryResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_aiMismatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalMismatchResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_similarProposals: {
    parameters: {
      query?: {
        /** @description Narrow to a single DAO by slug (default is cross-DAO). */
        dao?: string;
        /** @description Narrow to a proposal source_type. */
        type?: string;
        /** @description Lower bound on the proposal `created_at` (ISO-8601). */
        from?: string;
        /** @description Upper bound on the proposal `created_at` (ISO-8601). */
        to?: string;
        /** @description Max results, 1–20 (default 10). */
        limit?: number;
      };
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SimilarProposalsResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_aiForumSynthesis: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForumSynthesisResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_tally: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalTallyResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_listCrossDao: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc). Allowed: voting_starts_at, voting_ends_at, created_at, state_updated_at. */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited state values */
        state?: string;
        binding?: string;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorAnalyticsController_crossDao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CrossDaoActorDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_passRate: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
        proposal_type?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PassRateResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_participation: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
        proposal_type?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ParticipationResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_concentration: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConcentrationResponseDto'];
        };
      };
      /** @description No power-bearing delegation events in the requested window */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_delegationFlow: {
    parameters: {
      query?: {
        from?: string;
        to?: string;
        min_voting_power?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegationFlowResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_delegateLeaderboard: {
    parameters: {
      query?: {
        /** @description Max delegates to return (1–100, default 25). */
        limit?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegateLeaderboardResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_delegateAlignment: {
    parameters: {
      query: {
        delegate: string;
        limit?: number;
        cursor?: string;
        sort?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegateAlignmentResponseDto'];
        };
      };
      /** @description Redirect to canonical delegate filter */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_forumActivity: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForumActivityResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  SearchController_search: {
    parameters: {
      query: {
        /** @description Narrow to one entity type; omit to search all */
        type?: 'proposal' | 'dao' | 'actor';
        /** @description Max results per entity type (default 5, max 25) */
        limit?: number;
        /** @description Search query (min 1 char, max 200) */
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ForumThreadController_getThread: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        external_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForumThreadResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ForumThreadController_getThreadSynthesis: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        external_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForumSynthesisResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
