/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getData'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActorsController_getByAddress'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActorProposalsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActorVotesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/votes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['VotesController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/votes/{voter_address}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['VotesController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoController_sources'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/delegations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DelegationsController_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/delegates/{delegate_address}/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DelegationsController_current'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/actors/{address}/delegation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DelegationsController_actorDelegation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProposalController_listByDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProposalController_detail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/proposals/{source_type}/{source_id}/tally': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProposalController_tally'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/proposals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ProposalController_listCrossDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/actors/{address}/analytics/cross-dao': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ActorAnalyticsController_crossDao'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/proposal-pass-rate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoAnalyticsController_passRate'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/concentration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoAnalyticsController_concentration'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/delegation-flow': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoAnalyticsController_delegationFlow'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/analytics/delegate-alignment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['DaoAnalyticsController_delegateAlignment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daos/{slug}/forum/{external_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ForumThreadController_getThread'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActorAddressDto: {
      address: string;
      is_primary: boolean;
      source: string;
    };
    ActorDto: {
      actor_id: string;
      primary_address: string;
      display_name?: Record<string, never> | null;
      all_addresses: components['schemas']['ActorAddressDto'][];
    };
    ActorResponseDto: {
      data: components['schemas']['ActorDto'];
    };
    ProblemDto: {
      type: string;
      title: string;
      status: number;
      detail: string;
      instance: string;
      violations?: Record<string, never>[];
    };
    ActorProposalMetaDto: {
      confirmed: boolean;
    };
    ActorProposalListItemDto: {
      proposal_id: string;
      source_type: string;
      dao_slug: string;
      title?: Record<string, never> | null;
      state: string;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      created_at: string;
      _meta: components['schemas']['ActorProposalMetaDto'];
    };
    PaginationDto: {
      limit: number;
      next_cursor: Record<string, never> | null;
      has_more: boolean;
    };
    ActorProposalListResponseDto: {
      data: components['schemas']['ActorProposalListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    EmbeddedProposalLinksDto: {
      proposal: string;
    };
    EmbeddedProposalMetaDto: {
      links: components['schemas']['EmbeddedProposalLinksDto'];
    };
    EmbeddedProposalDto: {
      proposal_id: string;
      source_type: string;
      dao_slug: string;
      title?: Record<string, never> | null;
      state: string;
      created_at: string;
      voting_ends_at?: Record<string, never> | null;
      _meta: components['schemas']['EmbeddedProposalMetaDto'];
    };
    ActorVoteMetaDto: {
      confirmed: boolean;
    };
    ActorVoteListItemDto: {
      vote_id: string;
      voting_chain_id: string;
      proposal: components['schemas']['EmbeddedProposalDto'];
      primary_choice?: Record<string, never> | null;
      voting_power_reported: string;
      cast_at: Record<string, never> | null;
      _meta: components['schemas']['ActorVoteMetaDto'];
    };
    ActorVoteListResponseDto: {
      data: components['schemas']['ActorVoteListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    ActorLinkDto: {
      actor: string;
    };
    EmbeddedActorMetaDto: {
      links: components['schemas']['ActorLinkDto'];
    };
    VoterDto: {
      address: string;
      display_name?: Record<string, never> | null;
      _meta: components['schemas']['EmbeddedActorMetaDto'];
    };
    VoteMetaDto: {
      confirmed: boolean;
    };
    VoteListItemDto: {
      vote_id: string;
      voting_chain_id: string;
      voter: components['schemas']['VoterDto'];
      voting_power_reported: string;
      voting_power_verified: boolean;
      primary_choice: Record<string, never> | null;
      cast_at: Record<string, never> | null;
      reason?: Record<string, never> | null;
      _meta: components['schemas']['VoteMetaDto'];
    };
    VoteListResponseDto: {
      data: components['schemas']['VoteListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    VoteChoiceDto: {
      choice_index: number;
      weight: string;
    };
    VoteDetailDto: {
      vote_id: string;
      voting_chain_id: string;
      voter: components['schemas']['VoterDto'];
      voting_power_reported: string;
      voting_power_verified: boolean;
      primary_choice: Record<string, never> | null;
      cast_at: Record<string, never> | null;
      reason?: Record<string, never> | null;
      _meta: components['schemas']['VoteMetaDto'];
      choices: components['schemas']['VoteChoiceDto'][];
    };
    VoteDetailResponseDto: {
      data: components['schemas']['VoteDetailDto'] | null;
    };
    DaoLinksDto: {
      self: string;
    };
    DaoMetaDto: {
      last_updated_at: string;
      links: components['schemas']['DaoLinksDto'];
    };
    DaoListItemDto: {
      slug: string;
      name: string;
      description: string;
      website_url: string;
      forum_url: string;
      primary_token_address: string;
      primary_chain_id: string;
      _meta: components['schemas']['DaoMetaDto'];
    };
    DaoListResponseDto: {
      data: components['schemas']['DaoListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    DaoSourceDto: {
      source_type: string;
      config: {
        [key: string]: string | string[];
      };
    };
    DaoDetailDto: {
      slug: string;
      name: string;
      description: string;
      website_url: string;
      forum_url: string;
      primary_token_address: string;
      primary_chain_id: string;
      _meta: components['schemas']['DaoMetaDto'];
      sources: components['schemas']['DaoSourceDto'][];
    };
    DaoDetailResponseDto: {
      data: components['schemas']['DaoDetailDto'];
    };
    DaoSourceListResponseDto: {
      data: components['schemas']['DaoSourceDto'][];
    };
    DelegationActorLinksDto: {
      actor: string;
    };
    DelegationActorMetaDto: {
      links: components['schemas']['DelegationActorLinksDto'];
    };
    DelegationActorDto: {
      address: string;
      display_name?: Record<string, never> | null;
      _meta: components['schemas']['DelegationActorMetaDto'];
    };
    DelegationListItemDto: {
      delegation_id: string;
      delegator: components['schemas']['DelegationActorDto'];
      delegate: components['schemas']['DelegationActorDto'] | null;
      voting_power: string;
      block_number: string;
      event_type: string;
      /** @enum {string} */
      model: 'relationship-only' | 'power-bearing';
      tx_hash: string;
      created_at: Record<string, never> | null;
    };
    DelegationListResponseDto: {
      data: components['schemas']['DelegationListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    CurrentDelegatorsMetaDto: {
      as_of_block_number: string;
    };
    CurrentDelegatorsResponseDto: {
      data: components['schemas']['DelegationListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
      _meta: components['schemas']['CurrentDelegatorsMetaDto'];
    };
    OffchainDelegationDto: {
      platform: string;
      system: string;
      scope?: Record<string, never> | null;
      network: string;
      delegate_address: string;
      weight?: Record<string, never> | null;
      expires_at?: Record<string, never> | null;
    };
    ActorDelegationDto: {
      evm?: components['schemas']['DelegationListItemDto'] | null;
      offchain: components['schemas']['OffchainDelegationDto'][];
    };
    ActorDelegationResponseDto: {
      data: components['schemas']['ActorDelegationDto'];
    };
    ProposerDto: {
      address: string;
      display_name?: Record<string, never> | null;
    };
    ProposalLinksDto: {
      self: string;
      votes: string;
    };
    ProposalMetaDto: {
      confirmed: boolean;
      last_updated_at: string;
      links: components['schemas']['ProposalLinksDto'];
    };
    ProposalListItemDto: {
      dao_slug: string;
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      state: string;
      binding: boolean;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      proposer: components['schemas']['ProposerDto'];
      _meta: components['schemas']['ProposalMetaDto'];
    };
    ProposalListResponseDto: {
      data: components['schemas']['ProposalListItemDto'][];
      pagination: components['schemas']['PaginationDto'];
    };
    AragonProposalMetadataDto: {
      /** @enum {string} */
      kind: 'aragon_voting';
      app_address: string;
      app_version?: Record<string, never> | null;
      support_required_pct?: Record<string, never> | null;
      min_accept_quorum_pct?: Record<string, never> | null;
      main_phase_ends_at?: Record<string, never> | null;
      objection_phase_ends_at?: Record<string, never> | null;
      executed_at?: Record<string, never> | null;
    };
    SnapshotProposalMetadataDto: {
      /** @enum {string} */
      kind: 'snapshot';
      space_id: string;
      voting_type?: Record<string, never> | null;
      strategies?: Record<string, never> | null;
      ipfs_hash?: Record<string, never> | null;
      network?: Record<string, never> | null;
      scores_state?: Record<string, never> | null;
      flagged: boolean;
      /** @description Per-choice voting-power tally (0-indexed), summed from the full vote breakdown. Present for approval and weighted/quadratic proposals (whose tally the single primary_choice cannot represent); null otherwise. */
      choice_scores?: number[] | null;
    };
    DualGovernanceProposalMetadataDto: {
      /** @enum {string} */
      kind: 'dual_governance';
      /** @enum {string} */
      origin: 'aragon' | 'direct';
      dg_proposal_id: string;
      /** @enum {string} */
      status: 'submitted' | 'scheduled' | 'executed' | 'cancelled';
      executor: string;
      aragon_source_id?: Record<string, never> | null;
      submitted_at: string;
      scheduled_at?: Record<string, never> | null;
      executed_at?: Record<string, never> | null;
      cancelled_at?: Record<string, never> | null;
    };
    EasyTrackProposalMetadataDto: {
      /** @enum {string} */
      kind: 'easy_track';
      motion_id: string;
      factory_address: string;
      objection_ends_at: string;
      /** @enum {string} */
      state: 'active' | 'enacted' | 'objected' | 'rejected' | 'canceled';
    };
    ProposalActionDto: {
      action_index: number;
      target_address: string;
      target_chain_id: string;
      value_wei: string;
      function_signature?: Record<string, never> | null;
      calldata: string;
      decoded_function?: Record<string, never> | null;
      decoded_arguments?: Record<string, never> | null;
    };
    ProposalChoiceDto: {
      choice_index: number;
      value: string;
    };
    ProposalVotingDto: {
      voting_chain_id?: Record<string, never> | null;
      voting_machine_address?: Record<string, never> | null;
      voting_strategy_address?: Record<string, never> | null;
      creation_block: string;
    };
    ProposalPayloadDto: {
      payload_index: number;
      payload_id: string;
      payloads_controller_address: string;
      status: string;
      executed_at_destination?: Record<string, never> | null;
      unindexed_target_chain: boolean;
    };
    ProposalPayloadGroupDto: {
      target_chain_id: string;
      payloads: components['schemas']['ProposalPayloadDto'][];
    };
    OffchainDiscussionLinkDto: {
      platform: string;
      host: string;
      url: string;
      title?: Record<string, never> | null;
      /** @enum {string} */
      confidence: 'high' | 'medium' | 'low';
      last_activity_at?: Record<string, never> | null;
    };
    ProposalDetailDto: {
      dao_slug: string;
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      state: string;
      binding: boolean;
      voting_starts_at: Record<string, never> | null;
      voting_ends_at: Record<string, never> | null;
      proposer: components['schemas']['ProposerDto'];
      _meta: components['schemas']['ProposalMetaDto'];
      description: string;
      actions: components['schemas']['ProposalActionDto'][];
      choices: components['schemas']['ProposalChoiceDto'][];
      origin_chain_id: string;
      voting?: components['schemas']['ProposalVotingDto'] | null;
      payloads?: components['schemas']['ProposalPayloadGroupDto'][] | null;
      metadata?:
        | (
            | components['schemas']['AragonProposalMetadataDto']
            | components['schemas']['SnapshotProposalMetadataDto']
            | components['schemas']['DualGovernanceProposalMetadataDto']
            | components['schemas']['EasyTrackProposalMetadataDto']
          )
        | null;
      offchain_discussion_links: components['schemas']['OffchainDiscussionLinkDto'][];
    };
    ProposalDetailResponseDto: {
      data: components['schemas']['ProposalDetailDto'];
    };
    ProposalTallyChoiceDto: {
      choice_index: number;
      /** @description Summed voting power for the choice. UInt256 base units when source=votes; the raw per-choice score when source=choice_scores — interpret via `source`. */
      voting_power: string;
      voter_count: number;
      /** @description Share of participating power, 0–100, to two decimals. */
      pct: number;
    };
    ProposalTallyDto: {
      choices: components['schemas']['ProposalTallyChoiceDto'][];
      total_voting_power: string;
      total_voters: number;
      /**
       * @description Where the tally came from: `votes` (summed primary_choice) or `choice_scores` (a source-provided per-choice breakdown for approval/weighted proposals).
       * @enum {string}
       */
      source: 'votes' | 'choice_scores';
    };
    ProposalTallyResponseDto: {
      data: components['schemas']['ProposalTallyDto'];
    };
    CrossDaoSummaryDto: {
      dao_slug: string;
      votes_cast: number;
      proposals_proposed: number;
      current_voting_power: string;
      last_active_at?: Record<string, never> | null;
      alignment_with_majority_pct?: Record<string, never> | null;
    };
    AnalyticsMetaDto: {
      confirmed: boolean;
      derived_through?: Record<string, never> | null;
    };
    CrossDaoActorDto: {
      address: string;
      actor_id: string;
      daos: components['schemas']['CrossDaoSummaryDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    PassRateRowDto: {
      source_type: string;
      bucket: string;
      passed: number;
      failed: number;
      pass_rate?: Record<string, never> | null;
    };
    PassRateResponseDto: {
      data: components['schemas']['PassRateRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ConcentrationTopShareDto: {
      n_1: number;
      n_5: number;
      n_10: number;
      n_20: number;
    };
    ConcentrationRowDto: {
      bucket: string;
      gini: number;
      top_share: components['schemas']['ConcentrationTopShareDto'];
      effective_delegate_count: number;
      total_voting_power: string;
      delegate_count: number;
    };
    ConcentrationResponseDto: {
      data: components['schemas']['ConcentrationRowDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    DelegationFlowNodeDto: {
      actor_id: string;
      primary_address: string;
      display_name?: Record<string, never> | null;
      current_voting_power: string;
    };
    DelegationFlowEdgeDto: {
      delegator_actor_id: string;
      delegate_actor_id?: Record<string, never> | null;
      voting_power: string;
      block_number: string;
      event_type: string;
      created_at: string;
    };
    DelegationFlowResponseDto: {
      nodes: components['schemas']['DelegationFlowNodeDto'][];
      edges: components['schemas']['DelegationFlowEdgeDto'][];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    DelegateAlignmentFocalDto: {
      actor_id: string;
      address: string;
      display_name?: Record<string, never> | null;
    };
    DelegateAlignmentPeerDto: {
      actor_id: string;
      address: string;
      display_name?: Record<string, never> | null;
      vote_count: number;
      shared_proposals: number;
      alignment_score: number;
    };
    DelegateAlignmentResponseDto: {
      focal_delegate: components['schemas']['DelegateAlignmentFocalDto'];
      peers: components['schemas']['DelegateAlignmentPeerDto'][];
      pagination: components['schemas']['PaginationDto'];
      _meta: components['schemas']['AnalyticsMetaDto'];
    };
    ForumThreadLinkedProposalDto: {
      source_type: string;
      source_id: string;
      title: Record<string, never> | null;
      /** @enum {string} */
      confidence: 'high' | 'medium' | 'low';
    };
    ForumThreadDto: {
      /** @description Discourse topic id (the {external_id} in the URL). */
      external_id: string;
      host: string;
      /** @description Canonical link to the thread on the source Discourse instance. */
      source_url: string;
      title: Record<string, never> | null;
      /** @description Concatenated post bodies (the ingested thread content); no per-post breakdown. */
      raw_content: Record<string, never> | null;
      post_count: Record<string, never> | null;
      last_activity_at: Record<string, never> | null;
      linked_proposals: components['schemas']['ForumThreadLinkedProposalDto'][];
    };
    ForumThreadResponseDto: {
      data: components['schemas']['ForumThreadDto'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getData: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActorsController_getByAddress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorResponseDto'];
        };
      };
      /** @description Redirect to canonical primary address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorProposalsController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorProposalListResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorVotesController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorVoteListResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  VotesController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoteListResponseDto'];
        };
      };
      /** @description Redirect to canonical voter filter */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  VotesController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
        voter_address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VoteDetailResponseDto'];
        };
      };
      /** @description Redirect to canonical voter address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoDetailResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoController_sources: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DaoSourceListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegationListResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_current: {
    parameters: {
      query?: {
        as_of_block_number?: string;
      };
      header?: never;
      path: {
        slug: string;
        delegate_address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentDelegatorsResponseDto'];
        };
      };
      /** @description Redirect to canonical delegate address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DelegationsController_actorDelegation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActorDelegationResponseDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_listByDao: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_detail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalDetailResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_tally: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        source_type: string;
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalTallyResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ProposalController_listCrossDao: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        /** @description Comma-delimited sort fields (prefix with - for desc) */
        sort?: string;
        /** @description Comma-delimited DAO slugs */
        dao?: string;
        /** @description Comma-delimited proposal states */
        state?: string;
        source_type?: string;
        /** @description 0x-prefixed proposer address */
        proposer?: string;
        binding?: boolean;
        voting_starts_at_min?: string;
        voting_starts_at_max?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProposalListResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ActorAnalyticsController_crossDao: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CrossDaoActorDto'];
        };
      };
      /** @description Redirect to canonical actor address */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_passRate: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
        proposal_type?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PassRateResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_concentration: {
    parameters: {
      query?: {
        bucket?: 'daily' | 'weekly' | 'monthly';
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConcentrationResponseDto'];
        };
      };
      /** @description No power-bearing delegation events in the requested window */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_delegationFlow: {
    parameters: {
      query?: {
        from?: string;
        to?: string;
        min_voting_power?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegationFlowResponseDto'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  DaoAnalyticsController_delegateAlignment: {
    parameters: {
      query: {
        delegate: string;
        limit?: number;
        cursor?: string;
        sort?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DelegateAlignmentResponseDto'];
        };
      };
      /** @description Redirect to canonical delegate filter */
      301: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDto'];
        };
      };
    };
  };
  ForumThreadController_getThread: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
        external_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ForumThreadResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
