import { render, screen } from '@testing-library/react';

import { AIPanel } from './ai-panel';

const STATES = ['ok', 'loading', 'stale', 'rate-limited', 'failed'] as const;

describe('AIPanel', () => {
  it.each(STATES)('stays fenced (AI-labelled) in the %s state', (state) => {
    render(
      <AIPanel state={state} sourceHref="/src" provenance={{ model: 'm' }}>
        content
      </AIPanel>,
    );
    expect(screen.getByRole('region', { name: 'AI generated content' })).toBeInTheDocument();
  });

  it('exposes the provenance affordance', () => {
    render(<AIPanel provenance={{ model: 'claude-sonnet', promptVersion: 'v3' }}>x</AIPanel>);
    expect(screen.getByText('Generated by Kvorum')).toBeInTheDocument();
  });

  it('keeps the source reachable via View source', () => {
    render(<AIPanel sourceHref="/proposal/1/source">x</AIPanel>);
    expect(screen.getByRole('link', { name: /View source/ })).toHaveAttribute(
      'href',
      '/proposal/1/source',
    );
  });

  it('in the failed state fabricates nothing and links to the raw source', () => {
    render(
      <AIPanel state="failed" fallbackHref="/raw">
        should-not-render
      </AIPanel>,
    );
    expect(screen.queryByText('should-not-render')).not.toBeInTheDocument();
    expect(screen.getByRole('link', { name: /Read the proposal description/ })).toHaveAttribute(
      'href',
      '/raw',
    );
  });
});
