import type { CSSProperties, ReactNode } from 'react';

import { Skeleton } from './skeleton';
import { formatRelativeTime } from '@/lib/format';
import { cn } from '@/lib/utils';

export type AIPanelState =
  | 'ok'
  | 'loading'
  | 'stale'
  | 'rate-limited'
  | 'failed'
  /**
   * The feature is not built yet, as distinct from `failed`, where generation was attempted and did
   * not succeed. ADR-086 keeps the panel in place so the information architecture is stable and the
   * surface lights up when M5 ships, with no layout change.
   */
  | 'coming-soon';

export type AIProvenance = {
  model?: string;
  promptVersion?: string;
  generatedAt?: Date | number;
  inputHref?: string;
};

export type AIPanelProps = {
  state?: AIPanelState;
  /** Single-line label, e.g. "Summary by Kvorum". */
  label?: string;
  provenance?: AIProvenance;
  /** "View source" target — the original content the output is one click from. */
  sourceHref?: string;
  sourceLabel?: string;
  confidence?: 'high' | 'medium' | 'low';
  /** Raw-source link shown in the failed and coming-soon states (never fabricate content). */
  fallbackHref?: string;
  /** What the raw-source link points at, e.g. "Read the proposal description". */
  fallbackLabel?: string;
  /** Names the not-yet-built feature in the coming-soon state. */
  comingSoonLabel?: string;
  /** The AI content (rendered in ok / stale states). */
  children?: ReactNode;
  className?: string;
};

// Diagonal hatch — references the --ai-line token, so no hex leaks here.
const hatch: CSSProperties = {
  backgroundImage:
    'repeating-linear-gradient(135deg, transparent 0 14px, color-mix(in oklab, var(--ai-line), transparent 96%) 14px 15px)',
};

/**
 * The fenced container for every AI-generated output. Fenced in ALL states (△ mark,
 * hatch, 1.5px border, aria-label) so degraded output never leaks as un-fenced prose.
 * Provenance is one click away; the source is always reachable.
 */
export function AIPanel({
  state = 'ok',
  label = 'Summary by Kvorum',
  provenance,
  sourceHref,
  sourceLabel = 'View source',
  confidence,
  fallbackHref,
  fallbackLabel = 'Read the proposal description',
  comingSoonLabel = 'Summary',
  children,
  className,
}: AIPanelProps) {
  return (
    <section
      aria-label="AI generated content"
      style={hatch}
      className={cn('relative border-[1.5px] border-ai-line bg-ai-bg', className)}
    >
      <div className="flex items-center gap-2.5 border-b border-ai-line bg-ai-bg px-4 py-2.5 font-mono text-mono-body">
        <span className="inline-flex items-center gap-1.5 bg-ai-mark px-2 py-[3px] font-mono text-caption font-bold uppercase tracking-[0.08em] text-ai-bg">
          <span aria-hidden>△</span> AI
        </span>
        <span className="text-ink-2">{label}</span>
        {confidence === 'medium' && (
          <span className="border border-note px-1.5 text-micro uppercase text-note-ink">
            medium confidence
          </span>
        )}
        {confidence === 'low' && (
          <span className="border border-warn px-1.5 text-micro uppercase text-warn-ink">
            low confidence
          </span>
        )}
        {provenance?.model && (
          <span className="ml-auto text-caption text-ink-3">{provenance.model}</span>
        )}
      </div>

      <div className="border-b border-line-3 bg-bg-2 px-[18px] py-4 text-body-lg text-ink">
        {state === 'loading' && (
          <div className="space-y-2">
            <Skeleton className="h-3 w-full" />
            <Skeleton className="h-3 w-[92%]" />
            <Skeleton className="h-3 w-3/4" />
          </div>
        )}
        {(state === 'ok' || state === 'stale') && children}
        {state === 'rate-limited' && (
          <p className="font-mono text-small text-note-ink">
            Summary temporarily unavailable (rate limit) — retrying…
          </p>
        )}
        {state === 'failed' && (
          <p className="font-mono text-small text-warn-ink">
            Couldn’t generate a summary for this proposal.{' '}
            {fallbackHref && (
              <a href={fallbackHref} className="underline hover:text-warn">
                {fallbackLabel} →
              </a>
            )}
          </p>
        )}
        {state === 'coming-soon' && (
          <p className="font-mono text-small text-ink-3">
            {comingSoonLabel} is not generated yet.{' '}
            {fallbackHref && (
              <a href={fallbackHref} className="underline hover:text-ink">
                {fallbackLabel} →
              </a>
            )}
          </p>
        )}
      </div>

      <div className="flex items-center justify-between gap-4 bg-ai-bg px-4 py-2 font-mono text-caption text-ink-3">
        <div className="flex items-center gap-3">
          {provenance && (
            <details className="[&_summary]:cursor-pointer">
              <summary className="text-ink-2 hover:text-ink">Generated by Kvorum</summary>
              <div className="mt-1 space-y-0.5">
                {provenance.model && <div>model: {provenance.model}</div>}
                {provenance.promptVersion && <div>prompt: {provenance.promptVersion}</div>}
                {provenance.generatedAt != null && (
                  <div>generated: {formatRelativeTime(provenance.generatedAt)}</div>
                )}
                {provenance.inputHref && (
                  <div>
                    <a href={provenance.inputHref} className="text-ink-2 underline hover:text-ink">
                      input content →
                    </a>
                  </div>
                )}
              </div>
            </details>
          )}
          {state === 'stale' && provenance?.generatedAt != null && (
            <span className="text-note-ink">
              Generated {formatRelativeTime(provenance.generatedAt)} · inputs changed
            </span>
          )}
        </div>
        {sourceHref && (
          <a href={sourceHref} className="text-ink-2 hover:text-ink">
            {sourceLabel} ↗
          </a>
        )}
      </div>
    </section>
  );
}
