/**
 * Union of all event_type values written to archive_event.
 * Add a new protocol's event strings here when registering a new source.
 */
export type ArchiveEventType =
  | 'PayloadCreated'
  | 'PayloadQueued'
  | 'PayloadExecuted'
  | 'PayloadCancelled'
  | 'PayloadSent'
  | 'ProposalCreated'
  | 'ProposalQueued'
  | 'ProposalExecuted'
  | 'ProposalCanceled'
  | 'ProposalFailed'
  | 'ProposalResultsSent'
  | 'ProposalVoteStarted'
  | 'ProposalVoteConfigurationBridged'
  | 'VotingActivated'
  | 'VoteCast'
  | 'VoteEmitted'
  | 'DelegateChanged'
  | 'DelegateVotesChanged'
  | 'StartVote'
  | 'CastVote'
  | 'CastObjection'
  | 'ExecuteVote'
  | 'ChangeSupportRequired'
  | 'ChangeMinQuorum'
  | 'ChangeVoteTime'
  | 'ChangeObjectionPhaseTime'
  | 'ProposalSubmitted'
  | 'ProposalSubmittedMeta'
  | 'ProposalScheduled'
  | 'ProposalsCancelledTill'
  | 'CancelAllPendingProposalsExecuted'
  | 'CancelAllPendingProposalsSkipped'
  | 'DualGovernanceStateChanged'
  | 'NewSignallingEscrowDeployed'
  | 'EscrowMasterCopyDeployed'
  | 'ConfigProviderSet'
  | 'ProposalsCancellerSet'
  | 'ProposerRegistered'
  | 'ProposerExecutorSet'
  | 'ProposerUnregistered'
  | 'EmergencyModeActivated'
  | 'EmergencyModeDeactivated';
